language: csharp
install:
  # Clone, build and install ecsc
  - git clone --depth=5 https://github.com/jonathanvdc/ecsc
  - nuget restore ecsc/src/ecsc.sln
  - xbuild /p:Configuration=Release ecsc/src/ecsc.sln
  - chmod +x $(pwd)/ecsc/src/ecsc/bin/Release/*.exe
  - chmod +x $(pwd)/ecsc/src/ecsc/bin/Release/*.dll
  - ln -s $(pwd)/ecsc/src/ecsc/bin/Release/ecsc.exe /usr/local/bin/ecsc
script:
  # Build the project
  - make
