version: 0.1.0.{build}

install:
  - set VERNUM=0.1.0
  - echo %APPVEYOR_REPO_TAG%
  # Build packages as VERNUM-ci{build}
  - ps: if ($env:APPVEYOR_REPO_TAG -eq $True) { $env:PKG_VERSION = $env:VERNUM; } else { $env:PKG_VERSION = "$($env:VERNUM)-ci$($env:APPVEYOR_BUILD_NUMBER)"; }

  # Grab a compiled version of compare-test and add it to the PATH variable.
  - curl -L https://github.com/jonathanvdc/compare-test/releases/download/v0.1.4/compare-test.zip > compare-test.zip
  - mkdir compare-test
  - 7z x compare-test.zip -ocompare-test
  - set PATH=%PATH%;%cd%\compare-test
  # Clone ecsc, compile it and add it to the PATH variable.
  - git clone --depth=5 https://github.com/jonathanvdc/ecsc
  - nuget restore ecsc\src\ecsc.sln
  - msbuild /p:Configuration=Release ecsc\src\ecsc.sln
  - set PATH=%PATH%;%cd%\ecsc\src\ecsc\bin\Release
  # Add cygwin binaries to the PATH
  - set PATH=%PATH%;C:\cygwin\bin

build_script:
  # Build cs-wasm with csc
  - msbuild /p:Configuration=Release cs-wasm.sln
  # Build cs-wasm with ecsc
  - make all

after_build:
  # Create the NuGet package
  - nuget pack -Version %PKG_VERSION% libwasm.nuspec

test_script:
  # Run the tests
  - make test